# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWRiYmQ3ODJlZTRkMzFjNWVjNDVkOTUyMTBiOWQyZjM1YjQwNDg2YzI1ZGRkYmI2MDAxZmVlMWY1NWMyZjM4YmMxZWE1NGMwYWQyMDg4YWZkY2Q1OGY1M2ZhMjVkYTFkMTAzMjBjNTc5MmEyNmMzMDc1MDdiZjMyM2IzN2JhZTY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
